### ISSUE TITLE
TABLESWITCH issue: NegativeArraySizeException and VerifyError

### ISSUE THREAD

**Issue by tkhuu01** [umbcsops/j--#5]
This error is caused by any programs that make the padding equal to 4. See the next comment for more information.

Which causes (when using javap):
```
Error: A serious internal error has occurred: java.lang.NegativeArraySizeException
Please file a bug report, and include the following information:
java.lang.NegativeArraySizeException
	at com.sun.tools.classfile.Instruction.accept(Instruction.java:288)
	at com.sun.tools.javap.CodeWriter.writeInstr(CodeWriter.java:126)
	at com.sun.tools.javap.CodeWriter.writeInstrs(CodeWriter.java:108)
	at com.sun.tools.javap.ClassWriter.writeMethod(ClassWriter.java:512)
	at com.sun.tools.javap.ClassWriter.writeMethods(ClassWriter.java:412)
	at com.sun.tools.javap.ClassWriter.write(ClassWriter.java:217)
	at com.sun.tools.javap.JavapTask.write(JavapTask.java:784)
	at com.sun.tools.javap.JavapTask.writeClass(JavapTask.java:606)
	at com.sun.tools.javap.JavapTask.run(JavapTask.java:560)
	at com.sun.tools.javap.JavapTask.run(JavapTask.java:423)
	at com.sun.tools.javap.Main.main(Main.java:46)
```

when run:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: 
(class: Y, method: main signature: ([Ljava/lang/String;)V) Illegal instruction found at offset <some offset>
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)

```
This won't happen when using the `addLDCInstruction()` method in CLEmitter instead.

**Comment by tkhuu01** [comment]
This problem was caused by `pad = 4 - ((pc + 1) % 4);` in the `CLFlowInstruction` class inside the `CLInstruction` file, anytime the right hand side of the minus becomes 0, which makes `pad = 4`. This resulted in the bytes to be loaded into the wrong indices when converting them to bytecode in the `toBytes()` method.
Commit 6a21291 should fix this
