### ISSUE TITLE
LOOKUPSWITCH issue: java.lang.VerifyError when run

### ISSUE THREAD

**Issue by tkhuu01** [umbcsops/j--#6]
This error occurs in the same situations as in #5, but compiles fine.
Issue comes up when program is run and it produces:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: 
(class: Y, method: main signature: ([Ljava/lang/String;)V) Code stops in the middle of instruction  starting at offset <some offset>
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
```

**Comment by tkhuu01** [comment]
Commit 6a21291 should fix this. See #5 for more information.
